# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scheduler_pb2 as scheduler__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """Scheduler Service

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
                '/internal.proto.SchedulerService/CreateJob',
                request_serializer=scheduler__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=scheduler__pb2.CreateJobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/internal.proto.SchedulerService/GetJob',
                request_serializer=scheduler__pb2.GetJobRequest.SerializeToString,
                response_deserializer=scheduler__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.WatchJobStatus = channel.unary_stream(
                '/internal.proto.SchedulerService/WatchJobStatus',
                request_serializer=scheduler__pb2.WatchJobStatusRequest.SerializeToString,
                response_deserializer=scheduler__pb2.JobStatusUpdate.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/internal.proto.SchedulerService/RegisterWorker',
                request_serializer=scheduler__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=scheduler__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.RequestJob = channel.unary_unary(
                '/internal.proto.SchedulerService/RequestJob',
                request_serializer=scheduler__pb2.RequestJobRequest.SerializeToString,
                response_deserializer=scheduler__pb2.RequestJobResponse.FromString,
                _registered_method=True)
        self.ReportJobStatus = channel.unary_unary(
                '/internal.proto.SchedulerService/ReportJobStatus',
                request_serializer=scheduler__pb2.ReportJobStatusRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ReportJobStatusResponse.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """Scheduler Service

    """

    def CreateJob(self, request, context):
        """-------- Client APIs -------- 

        Client submits a new job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Client fetches job details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchJobStatus(self, request, context):
        """Client subscribes to real-time job updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """-------- Worker APIs -------- 

        Worker registers itself
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestJob(self, request, context):
        """Worker requests a job (pull-based)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportJobStatus(self, request, context):
        """Worker reports job execution status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=scheduler__pb2.CreateJobRequest.FromString,
                    response_serializer=scheduler__pb2.CreateJobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=scheduler__pb2.GetJobRequest.FromString,
                    response_serializer=scheduler__pb2.GetJobResponse.SerializeToString,
            ),
            'WatchJobStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchJobStatus,
                    request_deserializer=scheduler__pb2.WatchJobStatusRequest.FromString,
                    response_serializer=scheduler__pb2.JobStatusUpdate.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=scheduler__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=scheduler__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'RequestJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestJob,
                    request_deserializer=scheduler__pb2.RequestJobRequest.FromString,
                    response_serializer=scheduler__pb2.RequestJobResponse.SerializeToString,
            ),
            'ReportJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportJobStatus,
                    request_deserializer=scheduler__pb2.ReportJobStatusRequest.FromString,
                    response_serializer=scheduler__pb2.ReportJobStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'internal.proto.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('internal.proto.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """Scheduler Service

    """

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal.proto.SchedulerService/CreateJob',
            scheduler__pb2.CreateJobRequest.SerializeToString,
            scheduler__pb2.CreateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal.proto.SchedulerService/GetJob',
            scheduler__pb2.GetJobRequest.SerializeToString,
            scheduler__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/internal.proto.SchedulerService/WatchJobStatus',
            scheduler__pb2.WatchJobStatusRequest.SerializeToString,
            scheduler__pb2.JobStatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal.proto.SchedulerService/RegisterWorker',
            scheduler__pb2.RegisterWorkerRequest.SerializeToString,
            scheduler__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal.proto.SchedulerService/RequestJob',
            scheduler__pb2.RequestJobRequest.SerializeToString,
            scheduler__pb2.RequestJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/internal.proto.SchedulerService/ReportJobStatus',
            scheduler__pb2.ReportJobStatusRequest.SerializeToString,
            scheduler__pb2.ReportJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
